=== droganov/kata/schema/equipment.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "equipment.schema.json",
	"title": "Equipment",
	"description": "Средство выполнения (device): тело, снаряд, тренажёр, инвентарь, среда, свободный вес.",
	"type": "object",
	"additionalProperties": false,
	"required": ["id", "slug", "name", "canon_en", "kind", "exercises"],
	"properties": {
		"id": {
			"$ref": "common.schema.json#/definitions/uuid"
		},
		"slug": {
			"$ref": "common.schema.json#/definitions/slug"
		},
		"name": {
			"$ref": "common.schema.json#/definitions/text"
		},
		"canon_en": {
			"$ref": "common.schema.json#/definitions/text",
			"description": "Имя по международному каталогу"
		},
		"kind": {
			"type": "string",
			"enum": ["body", "apparatus", "machine", "tool", "environment", "free_weight"]
		},
		"exercises": {
			"$ref": "common.schema.json#/definitions/ref_list",
			"description": "Упражнения на этом средстве (Exercise.id) — обратная связь, симметрична Exercise.equipment"
		}
	}
}

=== droganov/kata/data/equipment.json
[
	{
		"id": "01a0889d-3852-7051-a039-c9778729a468",
		"slug": "body",
		"name": "Тело",
		"canon_en": "Bodyweight",
		"kind": "body",
		"exercises": [
			"01a0889d-3851-7468-b94f-0e0365b0548b",
			"01a0889d-388b-77b4-ae3d-5e4644a203e9",
			"01a0889d-38b8-7e11-bfa1-6cf8cc29fbfa",
			"01a0889d-38e3-70f2-9c37-84262503f144",
			"01a0889d-391e-75dd-97d5-d44c84dabdb6",
			"01a0889d-395c-79ac-b96c-32eaee32db30",
			"01a0889d-398d-7691-8a6d-1e3eb19f4aed",
			"01a0889d-39bd-7a4f-b780-4e3b89cb7b32",
			"01a0889d-39ef-76d8-a50f-4f7d6748285d",
			"01a0889d-3a1d-7012-acf6-cb7e0ada0917",
			"01a0889d-3a4a-7dc3-a71c-ce027250e73f",
			"01a0889d-3a79-7c51-8e10-183934b4a283",
			"01a0889d-3aaa-7b09-8435-b7a9d61e2a5d",
			"01a0889d-3adc-74a3-89cd-0159f4eba342",
			"01a0889d-3b0c-77b6-91b9-6a830b98c88e",
			"01a0889d-3b3f-73c9-908c-9750a1ef480d",
			"01a0889d-3b71-77ec-b668-66d4816a8cb3",
			"01a0889d-3ba3-77d7-8e85-0a1881e54f35",
			"01a0889d-3bd5-7c65-b91b-2cb1b4631b08",
			"01a0889d-3c08-7bc8-9a33-6b68bef7b4c2",
			"01a0889d-3c3e-78da-b3f1-1c81d8bcf9a4",
			"01a0889d-3c72-735f-9c50-a693bdf513a5",
			"01a0889d-3ca5-750e-a8ed-9c678b9612de",
			"01a0889d-3cd6-7b2f-9c44-9dc55f3ca5d5",
			"01a0889d-3d02-73a1-857e-98042e701fec",
			"01a0889d-3d31-7ae9-8b4c-a837208dd69c",
			"01a0889d-3d57-7d2f-9d48-9e98815640da",
			"01a0889d-3d86-7082-acbd-3139a7db005a",
			"01a0889d-3db8-7c1e-ac6f-870acf94838c",
			"01a0889d-3de7-7c2a-83c4-c4013124a6b5",
			"01a0889d-3e11-7444-a128-c6ebdb38c260",
			"01a0889d-3e42-7641-a915-b1077b617096",
			"01a0889d-3e70-7ca6-9493-ec14d4969b7f",
			"01a0889d-3e98-7090-8f79-4b2c77960c39",
			"01a0889d-3ec6-716a-8353-99b66051b722",
			"01a0889d-3ef0-753e-9061-481ae9a13492",
			"01a0889d-3f1b-70e8-813f-6f2fa4c88a22",
			"01a0889d-3f51-7977-8c75-aa7dc14b23aa",
			"01a0889d-3f7b-7862-a70b-4a98a4583aa8",
			"01a0889d-3fab-7eb9-b80e-57ecfea86d84",
			"01a0889d-3fd9-730d-b479-4c5479c7e017",
			"01a0889d-4017-794e-95cd-a5be2c3ca68c",
			"01a0889d-4045-7b8f-b335-9caba7dc641c",
			"01a0889d-406f-72ba-aa08-832bedfd1969",
			"01a0889d-40a2-7b1f-9f76-e710696cce36",
			"01a0889d-40d8-78d7-8459-1a5b9fed6e2d",
			"01a0889d-40fc-766b-b2cd-df089ead2989",
			"01a0889d-4129-78af-966c-c9165d4982e2",
			"01a0889d-4168-7358-9cf8-238ed32e3d3f",
			"01a0889d-41a4-7be9-b8fa-1a06ea69a4f3",
			"01a0889d-41d3-7170-b153-ca7c147d77a1",
			"01a0889d-4207-7e5f-ba31-ccbb6d5108ab",
			"01a0889d-4239-70cb-9cd7-b1cabd2d4628",
			"01a0889d-4262-7723-9864-4cd66d453e1b",
			"01a0889d-428e-7bce-ab0b-12f417c981bf",
			"01a0889d-42be-7dce-901c-8ef6e01ecd2a",
			"01a0889d-42f2-79aa-a864-8d1bc89db223",
			"01a0889d-4324-7068-8563-92732a0cd2e6",
			"01a0889d-434f-7308-8b38-628c4547b05a",
			"01a0889d-437b-755e-96b4-ac8d34254410",
			"01a0889d-43a6-712f-8a97-de928717f59e",
			"01a0889d-43d3-7a68-9264-db943a5ad42a",
			"01a0889d-43f3-79c8-a44d-0fa828570ed3",
			"01a0889d-451d-791b-8e72-a41b3accf890",
			"01a0889d-4ab9-7f9f-863d-49fd5124ca0b",
			"01a0889d-4bc8-7f72-ac4a-22535c2c282b",
			"01a0889d-513a-7a07-a8fc-8b87e0cd0ea0",
			"01a0889d-51a6-7569-9ec7-41ccafdb21ff",
			"01a0889d-521f-7650-a59c-aec81739697b",
			"01a0889d-55d4-7f80-965d-bd9f32c98eeb",
			"01a0889d-57b7-710f-a33d-eb33f5453842",
			"01a0889d-5b65-78b7-87a4-1cbb02ce8a13",
			"01a0889d-5b98-7bcc-8d97-e040cb7b8c81",
			"01a0889d-5cba-78af-a6e7-a0bc381f34a4",
			"01a0889d-5cf4-7732-963d-8183391b5136",
			"01a0889d-5ddb-78c2-b448-5342b2807d24",
			"01a0889d-5f8a-7d34-b8b2-0154d4fbe2fb",
			"01a0889d-6000-7466-95f5-8ecc456410c5",
			"01a0889d-6023-7f54-8830-c01240182e1f",
			"01a0889d-604f-78b8-94b5-58b8551e8efe",
			"01a0889d-607b-7268-94fa-ad103f96eebe",
			"01a0889d-609b-7454-adb4-5cd65cbf0a00",
			"01a0889d-60be-7602-87a1-a9b507d0a31c",
			"01a0889d-60e1-72a8-9685-d3a050153da4",
			"01a0889d-6107-7b1f-a7ef-20378d9e8f05",
			"01a0889d-61ff-7439-a6e3-702df64c56b8",
			"01a0889d-6225-7022-bc19-6d5b82fa1660",
			"01a0889d-6256-7787-bcd4-5d1804b63ae4",
			"01a0889d-6282-788a-b6e6-6c1eeb980247",
			"01a0889d-62a9-77d2-aa39-85a2abb60829",
			"01a0889d-62d2-77f4-81ff-1f16b2c38262",
			"01a0889d-62f6-7d08-87ae-1b951b80fda7",
			"01a0889d-631c-781a-92cd-a2d5db701d4a",
			"01a0889d-6349-7934-a190-5392a980b2f2",
			"01a0889d-636a-75ad-a2cf-d93ca7bf2de0",
			"01a0889d-6391-775e-a9f5-5290f80dd764",
			"01a0889d-63b6-78e1-986e-1f60e4453caf",
			"01a0889d-63d9-7471-9537-b165b6d64672",
			"01a0889d-6402-703f-807d-3943e000618f",
			"01a0889d-6480-77f6-b210-ed0f260fa1e0",
			"01a0889d-6499-781f-ab78-7b9b2409e8a0",
			"01a0889d-64c2-7a91-a979-859983680a0d",
			"01a0889d-64e9-76c8-aae2-6a52a2a3402c",
			"01a0889d-6510-7c1b-8dbc-387d6cffa07c",
			"01a0889d-6539-7bab-83e1-ca4446cf38be",
			"01a0889d-679d-73f5-b6ee-40eb5d289e4e",
			"01a0889d-67f2-7c3e-8055-867fa8f4ad38",
			"01a0889d-6823-7ce8-a51d-060f6d986262",
			"01a0889d-6849-7df5-a535-550aaa9f0437",
			"01a0889d-6897-7209-bac6-ac1b444cd092",
			"01a0889d-68c3-794e-bc00-1df4f7def667",
			"01a0889d-697d-75fd-9a35-49b702b7e18a",
			"01a0889d-69a3-7b34-aa8c-f29784ae269a",
			"01a0889d-6a1c-7068-8fb7-f76dd4160266",
			"01a0889d-6a6d-71c4-a264-0725fc244c12",
			"01a0889d-6a93-7f98-9d37-67a631eb7137",
			"01a0889d-6aba-745f-950f-521679dee42a",
			"01a0889d-6add-7e55-98c3-458e49e5fbf6",
			"01a0889d-6b23-7095-bc39-c502b2da8e46",
			"01a0889d-6b4d-7b5c-b0a9-d0e8ff6517e7",
			"01a0889d-6b74-7f18-8538-149cb697e0a6",
			"01a0889d-6b97-74fd-85b4-fff47c2f5b26",
			"01a0889d-6bbb-7d0b-ab01-b9040d8f2989",
			"01a0889d-6be4-7708-8d7f-9823deeb51fb",
			"01a0889d-6c09-7542-901e-704766e08142",
			"01a0889d-6c22-76c2-8275-ffd2594223b1",
			"01a0889d-6c55-7e0e-9886-c3b83e900b3e",
			"01a0889d-6c7c-7473-bad6-eff91a6ec325",
			"01a0889d-6ca3-761e-a74b-a71c8f2b9b09",
			"01a0889d-6d04-77b6-b7b8-5330b9827791",
			"01a0889d-6d30-798d-b1a1-73366c3b68ba",
			"01a0889d-6d50-7f02-96c6-e4754fa99e51",
			"01a0889d-6d6c-73d9-a281-846be2453b1c",
			"01a0889d-6dcb-7782-ba79-d5b4d1b043c9",
			"01a0889d-6df8-7aae-98bb-2efdcf2597fc",
			"01a0889d-6e5d-7728-a766-737404715826",
			"01a0889d-6e8a-758a-8ace-ae382e5e9d7c",
			"01a0889d-6ea8-7428-88cb-7e8f0f42743b",
			"01a0889d-6ed6-7c06-bcef-cfc731f4ae85",
			"01a0889d-6efe-76af-9352-9f6e87a1f50b",
			"01a0889d-6f63-7f40-a4cb-e64227337844",
			"01a0889d-6f90-7d7c-a065-9270cd35ff3d",
			"01a0889d-6fbe-73aa-aff6-89c7a93de015",
			"01a0889d-6feb-7169-a461-8c6a8668df87",
			"01a0889d-7017-7630-921a-240cf7520d51",
			"01a0889d-7049-7eae-b620-9f726dab3bf5",
			"01a0889d-7070-7342-b9b5-5a5c085560f0",
			"01a0889d-70a2-7c05-a3b1-f3aa74ca2082",
			"01a0889d-70fa-718f-99f4-52af0028833c",
			"01a0889d-718b-7172-b8fc-d59d73cfe4f8",
			"01a0889d-71be-75e0-9d1c-59300fff59c5",
			"01a0889d-71ed-7823-8508-30ec7ad2931a",
			"01a0889d-72b4-7c15-bde3-051b411a5cdf",
			"01a0889d-72e7-7628-af19-1869e6f435ff",
			"01a0889d-730c-7b05-8db4-a9b572a35997",
			"01a0889d-733d-73e5-be80-27b507fbeed7",
			"01a0889d-7369-7a2a-8273-f73b654ca892",
			"01a0889d-738d-7e18-97ff-5f30d18809b4",
			"01a0889d-73b8-734b-b346-bd716c79b72e",
			"01a0889d-73d9-771f-b23e-df38b998542d",
			"01a0889d-746f-7ffc-a6a9-85d541c0c79f",
			"01a0889d-749c-7c9d-8927-b4d7c5528830",
			"01a0889d-74ba-7531-9b31-33e76b00c73b",
			"01a0889d-74de-766f-8787-bfa1b7c0c4a8",
			"01a0889d-7508-71c5-9e2b-67287cd00f59",
			"01a0889d-7562-7bd3-800c-fd812a66773f",
			"01a0889d-7579-709c-af60-b682cfd44885",
			"01a0889d-7592-7545-bc9f-1167cc62fb92",
			"01a0889d-75bc-7683-8cec-0c4be5f7f235",
			"01a0889d-75e5-7361-85e5-a195b5a6b420",
			"01a0889d-7602-7ad4-a1bb-00602610d5ad",
			"01a0889d-7616-7238-ae35-1d978f558439",
			"01a0889d-7641-7cb4-b47a-d74bd2df3d72",
			"01a0889d-766e-796d-865b-b4540d2a4c2a",
			"01a0889d-76a3-7f30-abeb-b9b5a82049ba",
			"01a0889d-76d6-7a67-b872-eb3c35d3fd55",
			"01a0889d-770c-77ce-a0b9-3d7ee5bbff58",
			"01a0889d-773a-70b3-931e-8424840f0fd6",
			"01a0889d-776c-7c5d-9daa-6887e47a2eef",
			"01a0889d-77a2-761a-ae24-df38bd675b74",
			"01a0889d-77dd-7d47-a292-74c0d94a0ee3",
			"01a0889d-7814-7b2a-9717-7cc83b200b0f",
			"01a0889d-7843-7706-ad9c-dd68f6e28315",
			"01a0889d-7876-7186-a330-8d7835a21a40",
			"01a0889d-78a9-71b1-9641-3a8d3b47740d",
			"01a0889d-78e4-7db5-8209-0157ba6d681b",
			"01a0889d-791d-75bb-b0ee-d901b6685038",
			"01a0889d-7962-7c7e-a9cc-bf9b3f8344b1",
			"01a0889d-79a1-7f9b-b3e1-1a07b3d76e3c",
			"01a0889d-79d4-7976-95ce-fa7d2196a10e",
			"01a0889d-7a07-70f4-8695-22ac3573b14f",
			"01a0889d-7a47-7aa5-aa35-0780c90112d1",
			"01a0889d-7a83-7996-8944-5dd4cebe1642",
			"01a0889d-7ab7-7472-90ab-c16aea850892",
			"01a0889d-7ae6-7b30-85e1-00d8a2c7d59a",
			"01a0889d-7b2c-71d6-a87f-7ae450d2fbd5",
			"01a0889d-7b5f-7e81-aad8-61d8fb833f06",
			"01a0889d-7b9b-72e0-9d45-1d77f49af5bb",
			"01a0889d-7bcd-7646-b0f3-51eff1d1caad",
			"01a0889d-7bf7-762c-857f-39d3c3052d92",
			"01a0889d-7c28-7f20-9cd3-4e12a0e1a856",
			"01a0889d-7c54-7a1f-93c6-d89fbcca992b",
			"01a0889d-7c8a-7f72-9ef1-fcf4f136740e",
			"01a0889d-7ccf-72ba-a98e-89cfc80e8bc4",
			"01a0889d-7d16-7bb0-9c2a-7bca328fa631",
			"01a0889d-7d45-7ac8-bdc8-b4841f398489",
			"01a0889d-7d88-74d7-8954-75b6a66265f8",
			"01a0889d-7db6-7065-9fde-bc78525fce98",
			"01a0889d-7de8-7a95-ab73-f75df8069227",
			"01a0889d-7e1e-7096-b280-f0059dacd9f8",
			"01a0889d-7e51-7c24-8d7e-a9a096190739",
			"01a0889d-7e84-7f3b-856d-894305f5185d",
			"01a0889d-7ec6-7f89-9666-9f29522f5e92",
			"01a0889d-7efe-79ff-8452-2029afa8350a",
			"01a0889d-7f35-7d52-a290-ba65ddbd0855",
			"01a0889d-7f6c-7137-8f60-befefe9c0ea6",
			"01a0889d-7fa5-7a80-a07c-142f83f945a3",
			"01a0889d-7fdd-75b8-a1b5-a8f1e83119c4",
			"01a0889d-8013-72f3-ad2a-ccedf25272f9",
			"01a0889d-804d-70fe-bd3e-d1466a7b7bb2",
			"01a0889d-808e-7c3d-96b0-8e1ddb838b96",
			"01a0889d-80c5-7f39-9836-de8ce030fc81",
			"01a0889d-8107-7928-bbca-9ed6cb566b02",
			"01a0889d-8144-79f2-897d-1c7a7222e063",
			"01a0889d-817b-7714-bc62-58077c0028d0",
			"01a0889d-81a9-71d0-9a61-145a52331fa2",
			"01a0889d-81e4-7dce-bf54-e3620a248d21",
			"01a0889d-820d-7c7b-9256-718d2c341397",
			"01a0889d-8242-7670-afa8-f4ad66eecd66",
